report_an_issue:
  name: Send problem report
  description: Send a report about any problem with your Smart Home
  fields:
    only_description:
      description: True for repeated errors
      name: Only Description
      required: true
      selector:
        boolean:
    description:
      description: Describe your problem
      name: Description
      required: true
      selector:
        text: